name: kpler-ds
channels: [conda-forge]
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  # notebook
  - ipykernel
  - jupyterlab
  - jupytext
  - nbstripout
  # ds
  - numpy
  - pandas
  - polars
  - pyarrow
  - fastparquet
  - duckdb
  - tabulate
  # visualization
  - matplotlib
  - seaborn
  - plotly
  # ml
  - scikit-learn
  - xgboost
  - lightgbm
  - catboost
  - statsmodels
  - optuna
  - shap
  # gis
  - geopandas
  - shapely
  - pyproj
  - geopy
  - folium
  - networkx
  - keplergl
  - pydeck
  - h3
  # other
  - ydata-profiling
  - pip
  - pip:
      - nbformat>=5.10    
      - haversine         
